# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestOlxmotokategorie():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_olxmotokategorie(self):

        self.driver.get("https://www.olx.pl/")
        self.driver.set_window_size(1552, 840)
        time.sleep(1)
        self.driver.find_element(By.CSS_SELECTOR, ".cat-icon-5").click()
        time.sleep(1)
        self.driver.find_element(By.CSS_SELECTOR, "#bottom5 > ul:nth-child(2) > li:nth-child(1) > a:nth-child(1)").click()
        time.sleep(2)
        self.driver.find_element_by_xpath( "/html/body/div[3]/header/div[2]/div/form/noindex/div/fieldset[2]/ul/li[1]/ul/li[1]/div[2]/a").click()
        time.sleep(3)
        self.driver.find_element_by_xpath("/html/body/div[3]/header/div[2]/div/form/noindex/div/fieldset[2]/ul/li[1]/ul/li[1]/div[2]/ul/li[3]/a").click()
        time.sleep(1)
        assert self.driver.find_element_by_xpath("/html/body/div[3]/div[5]/section/div[1]/div[1]/div[1]/ul/li[4]/h1").text == "Używane Alfa Romeo sprzedam - OLX.pl"
        time.sleep(1)
        self.driver.get("https://www.olx.pl/")
        time.sleep(1)
        self.driver.find_element(By.CSS_SELECTOR, ".cat-icon-5").click()
        time.sleep(1)
        self.driver.find_element(By.CSS_SELECTOR,"#bottom5 > ul:nth-child(2) > li:nth-child(2) > a:nth-child(1)").click()
        time.sleep(2)

        self.driver.find_element_by_xpath("/html/body/div[3]/header/div[2]/div/form/noindex/div/fieldset[2]/ul/li[1]/ul/li[2]/div[2]/a").click()
        time.sleep(3)
        self.driver.find_element_by_xpath("/html/body/div[3]/header/div[2]/div/form/noindex/div/fieldset[2]/ul/li[1]/ul/li[2]/div[2]/ul/li[44]/label[2]").click()
        woj = self.driver.find_element_by_xpath('//*[@id="cityField"]')
        woj.click()
        time.sleep(2)
        self.driver.find_element_by_xpath("/html/body/div[3]/header/div[2]/div/form/fieldset/div/noindex/table/tbody/tr/td[2]/div/div/div/div[4]/ul/li[1]/a").click()
        time.sleep(1)
        assert self.driver.find_element_by_xpath(
            "/html/body/div[3]/div[5]/section/div[1]/div[1]/div[1]/ul/li[3]/h1").text == "Małopolskie Używane motocykle i skutery sprzedam - OLX.pl"

        self.driver.find_element(By.ID, "search-text").send_keys("opel astra")
        self.driver.find_element(By.ID, "search-submit").click()
        self.driver.execute_script("window.scrollTo(0,544)")
        time.sleep(4)
        assert self.driver.find_elements_by_xpath("/html/body/div[3]/div[5]/section/div[2]/div/div[3]/span[3]").text == "nowe ogłoszenia na pewno się pojawią"


if __name__ == '__main__':
    pytest.main()
